"""client email primary, optional phone, collect_phone

Revision ID: 054a3a76fc72
Revises: a7c2e9f1d406
Create Date: 2026-06-29 00:02:25.865540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054a3a76fc72'
down_revision = 'a7c2e9f1d406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('collect_phone', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.alter_column('phone_e164',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.drop_constraint('uq_clients_phone', type_='unique')
        batch_op.create_unique_constraint('uq_clients_email', ['business_id', 'email'])

    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.alter_column('phone_e164',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_verification_codes_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_codes_email'))
        batch_op.alter_column('phone_e164',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.drop_column('email')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint('uq_clients_email', type_='unique')
        batch_op.create_unique_constraint('uq_clients_phone', ['business_id', 'phone_e164'])
        batch_op.alter_column('phone_e164',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.drop_column('email')

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('collect_phone')

    # ### end Alembic commands ###
