"""public page content fields, staff bio

Revision ID: 089fc324c580
Revises: 054a3a76fc72
Create Date: 2026-06-29 02:31:31.479249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089fc324c580'
down_revision = '054a3a76fc72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('about_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('contact_phone', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('instagram_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('facebook_url', sa.String(length=512), nullable=True))
        batch_op.add_column(
            sa.Column('gallery_urls', sa.JSON(), nullable=False, server_default='[]')
        )

    with op.batch_alter_table('staff_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_members', schema=None) as batch_op:
        batch_op.drop_column('bio')

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('gallery_urls')
        batch_op.drop_column('facebook_url')
        batch_op.drop_column('instagram_url')
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('about_text')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
