"""email verified at and registration code fields on users

Revision ID: 0fb5cf19f1ef
Revises: 7ace6b315eac
Create Date: 2026-06-30 02:30:46.727349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fb5cf19f1ef'
down_revision = '7ace6b315eac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verify_code_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_verify_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('email_verify_attempts', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verify_attempts')
        batch_op.drop_column('email_verify_expires_at')
        batch_op.drop_column('email_verify_code_hash')

    # ### end Alembic commands ###
