"""add reminder_sent_at to appointments

Revision ID: 7042c53b73d7
Revises: c228ffcf1ed3
Create Date: 2026-06-23 18:14:44.220177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7042c53b73d7'
down_revision = 'c228ffcf1ed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('reminder_sent_at')

    # ### end Alembic commands ###
