"""add verification codes and daily sms cap

Revision ID: c228ffcf1ed3
Revises: c534b1aa03d0
Create Date: 2026-06-23 01:30:09.185107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c228ffcf1ed3'
down_revision = 'c534b1aa03d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('phone_e164', sa.String(length=32), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_codes_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_codes_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_codes_phone_e164'), ['phone_e164'], unique=False)

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_sms_cap', sa.Integer(), nullable=False, server_default='50'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('daily_sms_cap')

    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_codes_phone_e164'))
        batch_op.drop_index(batch_op.f('ix_verification_codes_ip_address'))
        batch_op.drop_index(batch_op.f('ix_verification_codes_business_id'))

    op.drop_table('verification_codes')
    # ### end Alembic commands ###
