"""vouchers, staff time off, staff photo, business website/marketing/loyalty settings

Revision ID: d99ce4a54e44
Revises: ef3c5fb717a0
Create Date: 2026-06-29 21:57:28.614077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99ce4a54e44'
down_revision = 'ef3c5fb717a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_time_off',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_time_off', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_time_off_staff_id'), ['staff_id'], unique=False)

    op.create_table('vouchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('percent_off', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_appointment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['consumed_appointment_id'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vouchers_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vouchers_client_id'), ['client_id'], unique=False)

    with op.batch_alter_table('discount_codes', schema=None) as batch_op:
        batch_op.drop_index('ix_discount_codes_business_id')

    op.drop_table('discount_codes')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voucher_code', sa.String(length=32), nullable=True))
        batch_op.drop_column('discount_code')

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_url', sa.String(length=512), nullable=True))
        batch_op.add_column(
            sa.Column('marketing_enabled', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(
            sa.Column('loyalty_enabled', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(
            sa.Column('loyalty_every_n', sa.Integer(), nullable=False, server_default='10')
        )

    with op.batch_alter_table('staff_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_members', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('loyalty_every_n')
        batch_op.drop_column('loyalty_enabled')
        batch_op.drop_column('marketing_enabled')
        batch_op.drop_column('website_url')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_code', sa.VARCHAR(length=32), nullable=True))
        batch_op.drop_column('voucher_code')

    op.create_table('discount_codes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('business_id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=32), nullable=False),
    sa.Column('percent_off', sa.INTEGER(), nullable=False),
    sa.Column('max_uses', sa.INTEGER(), nullable=True),
    sa.Column('use_count', sa.INTEGER(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'code', name='uq_discount_codes_code')
    )
    with op.batch_alter_table('discount_codes', schema=None) as batch_op:
        batch_op.create_index('ix_discount_codes_business_id', ['business_id'], unique=False)

    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vouchers_client_id'))
        batch_op.drop_index(batch_op.f('ix_vouchers_business_id'))

    op.drop_table('vouchers')
    with op.batch_alter_table('staff_time_off', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_time_off_staff_id'))

    op.drop_table('staff_time_off')
    # ### end Alembic commands ###
