"""add trial_started_at to businesses

Revision ID: f81464b972cd
Revises: 0fb5cf19f1ef
Create Date: 2026-06-30 17:47:42.611140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f81464b972cd'
down_revision = '0fb5cf19f1ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trial_started_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('trial_started_at')

    # ### end Alembic commands ###
